# linux builds and publishes ooniprobe for Linux
name: linux
on:
  push:
    branches:
      - "main"
    tags:
      - "v*"
jobs:
  build:
    runs-on: "ubuntu-20.04"
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: "1.17.3"
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: go build -o ooniprobe-linux-amd64 -v ./cmd/ooniprobe
      - run: |
          tag=$(echo $GITHUB_REF | sed 's|refs/tags/||g')
          gh release create -p $tag --target $GITHUB_SHA || true
          gh release upload $tag --clobber ooniprobe-linux-amd64
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
