# macos builds ooniprobe for macos
name: macos
on:
  push:
    branches:
      - "main"
    tags:
      - "v*"
jobs:
  build:
    runs-on: "macos-10.15"
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: "1.17.3"
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: go build -o ooniprobe-darwin-amd64 -v ./cmd/ooniprobe
      - run: |
          tag=$(echo $GITHUB_REF | sed 's|refs/tags/||g')
          gh release create -p $tag $GITHUB_SHA || true
          gh release upload --clobber ooniprobe-darwin-amd64
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
