# windows builds ooniprobe for Windows
name: windows
on:
  push:
    branches:
      - "main"
jobs:
  build:
    runs-on: "ubuntu-20.04"
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: "1.17.3"
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: sudo apt install mingw-w64
      - run: GOOS=windows GOARCH=amd64 CGO_ENABLED=1 CC=x86_64-w64-mingw32-gcc go build -v ./cmd/ooniprobe
